/**
 * generated-marker — the marker every `rad generate` output carries, and the
 * check for it (#171 part 2, amendment 1).
 *
 * Constraints:
 * - Imports nothing local: generate.js and install-manifest.js both depend on
 *   this module, so it must never depend on either (no import cycle).
 * - generate.js re-exports GENERATED_MARKER and hasGeneratedMarker unchanged;
 *   this is the one definition.
 */

/** The stable phrase every generated file carries; the marker check keys on it. */
export const GENERATED_MARKER = 'generated by rad generate; edit the source, not this file';

/** Matches the `(source: <path>)` suffix of a marker line, in either comment form. */
const SOURCE_RE = / \(source: ([^()\s]+)\)(?: -->)?$/;

/**
 * The line carrying the generated marker in its defined position — the first
 * line (`#` comment), or the line right after the frontmatter (HTML comment) —
 * or null when there is none.
 */
function markerLineOf(content) {
  const lines = content.split('\n');
  if (lines[0].startsWith('# ') && lines[0].includes(GENERATED_MARKER)) return lines[0];
  if (lines[0] !== '---') return null;
  const close = lines.indexOf('---', 1);
  const next = close > 0 ? lines[close + 1] ?? '' : '';
  return next.startsWith('<!-- ') && next.includes(GENERATED_MARKER) ? next : null;
}

/** True when `content` carries the generated marker in its defined position. */
export function hasGeneratedMarker(content) {
  return markerLineOf(content) !== null;
}

/** The `source:` path recorded in `content`'s marker line, or null (no marker, or no parseable source). */
export function generatedSource(content) {
  const line = markerLineOf(content);
  return line === null ? null : line.match(SOURCE_RE)?.[1] ?? null;
}
