/**
 * generate — one assistant-neutral source, generated Claude Code and Codex
 * wrappers (#171 part 1).
 *
 * Sources live under <root>/.rad/:
 *   .rad/skills/<name>/SKILL.md   frontmatter name, description, targets
 *                                  (+ optional claude.md / codex.md body overrides)
 *   .rad/agents/<name>.md         Claude agent frontmatter + optional codex: mapping
 *
 * Outputs (every one carries the generated marker):
 *   .claude/commands/<subdir>/<file>.md, .claude/skills/<name>/SKILL.md,
 *   .agents/skills/<name>/SKILL.md (+ agents/openai.yaml), .claude/agents/<name>.md,
 *   .codex/agents/<name>.toml
 *
 * Constraints:
 * - readSources / renderOutputs never throw: every source problem is returned
 *   as an error string that starts with the offending path.
 * - Nothing is followed: sources, output files and every output ancestor are
 *   lstat'ed; a symlink is an error (source) or a conflict (output).
 * - An unmarked file at an output path is a conflict and is never overwritten.
 * - Output is deterministic: sorted, stable key order, one trailing newline.
 * - TOML is written by hand. developer_instructions is a multi-line LITERAL
 *   string ('''...'''), which cannot contain ''' or control characters other
 *   than tab and newline, so such a body is rejected rather than escaped.
 *
 * js-yaml is imported lazily (same convention as config.js loadConfig).
 */

import { lstatSync, readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { isSafeRelPath } from './install-manifest.js';

/** The stable phrase every generated file carries; the marker check keys on it. */
export const GENERATED_MARKER = 'generated by rad generate; edit the source, not this file';
/** Source directories, relative to the root. */
export const SOURCE_DIR = '.rad';
const SKILLS_DIR = `${SOURCE_DIR}/skills`;
const AGENTS_DIR = `${SOURCE_DIR}/agents`;
const SKILL_FILE = 'SKILL.md';
/** Per-assistant body overrides allowed next to SKILL.md. */
const OVERRIDE_FILES = Object.freeze({ claude: 'claude.md', codex: 'codex.md' });
/** Every directory a generated file can land under (scanned for orphans). */
export const OUTPUT_ROOTS = Object.freeze(['.claude/commands', '.claude/skills', '.claude/agents', '.agents/skills', '.codex/agents']);
/** The only body token, and what it becomes per assistant. */
const ARGS_TOKEN = 'args';
const ARGS_TEXT = Object.freeze({ claude: '$ARGUMENTS', codex: 'the text the user wrote after the skill name' });
const TOKEN_RE = /\{\{([^}]*)\}\}/g;
const NAME_RE = /^[a-z0-9][a-z0-9-]*$/;
const COMMAND_PREFIX = 'command:';
const SKILL_TARGET_KEYS = Object.freeze(['claude', 'codex', 'codex_implicit']);
const SKILL_KEYS = Object.freeze(['name', 'description', 'targets']);
const AGENT_KEYS = Object.freeze(['name', 'description', 'model', 'tools', 'roles', 'codex']);
const AGENT_REQUIRED = Object.freeze(['name', 'description', 'model', 'tools']);
const SANDBOX_MODES = Object.freeze(['read-only', 'workspace-write']);
/** Sequence that cannot appear inside a TOML multi-line literal string. */
const TOML_LITERAL_DELIM = "'''";
/** Control characters TOML literal strings forbid (tab and LF are allowed). */
const TOML_LITERAL_FORBIDDEN = /[\u0000-\u0008\u000B-\u001F\u007F]/;
/** A YAML scalar safe to emit unquoted. */
const PLAIN_SCALAR = /^[A-Za-z][A-Za-z0-9 ._,/-]*$/;
/** Plain words YAML would read back as a boolean or null. */
const YAML_RESERVED = /^(true|false|yes|no|on|off|null)$/i;
const IGNORED_NAMES = new Set(['.DS_Store']);

const isPlainObject = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);
const isNonEmptyString = (v) => typeof v === 'string' && v.trim() !== '';

/** lstat that returns null for an absent path (any other error propagates). */
function lstatOrNull(path) {
  try {
    return lstatSync(path);
  } catch (err) {
    if (err.code === 'ENOENT' || err.code === 'ENOTDIR') return null;
    throw err;
  }
}

/** Read a regular file as LF text: { text } or { error } (a symlink is refused). */
function readRegular(root, rel) {
  const st = lstatOrNull(join(root, rel));
  if (!st) return { error: `${rel}: missing` };
  if (!st.isFile()) return { error: `${rel}: not a regular file (symlinks are refused)` };
  return { text: readFileSync(join(root, rel), 'utf8').replace(/\r\n/g, '\n') };
}

/** Split `---` frontmatter from the body and parse it: { data, body } or { error }. */
async function parseFrontmatter(rel, text) {
  const match = /^---\n([\s\S]*?)\n---(?:\n|$)/.exec(text);
  if (!match) return { error: `${rel}: missing --- frontmatter block` };
  try {
    const { default: yaml } = await import('./vendor/js-yaml.mjs');
    const data = yaml.load(match[1]);
    if (!isPlainObject(data)) return { error: `${rel}: frontmatter must be a YAML mapping` };
    return { data, body: text.slice(match[0].length) };
  } catch (err) {
    return { error: `${rel}: cannot parse frontmatter: ${err.message.split('\n')[0]}` };
  }
}

/** Errors common to every source: unknown keys, name and description. */
function identityErrors(rel, data, allowedKeys, expectedName) {
  const errors = Object.keys(data).filter((k) => !allowedKeys.includes(k)).map((k) => `${rel}: unknown key '${k}'`);
  if (!isNonEmptyString(data.name)) errors.push(`${rel}: missing name`);
  else if (!NAME_RE.test(data.name)) errors.push(`${rel}: name ${JSON.stringify(data.name)} is not kebab-case`);
  else if (data.name !== expectedName) errors.push(`${rel}: name '${data.name}' does not match '${expectedName}'`);
  if (!isNonEmptyString(data.description)) errors.push(`${rel}: missing description`);
  return errors;
}

/** Parse targets.claude: { value } or { error }. */
function claudeTarget(rel, raw) {
  if (raw === 'skill') return { value: { kind: 'skill' } };
  if (typeof raw === 'string' && raw.startsWith(COMMAND_PREFIX)) {
    const path = raw.slice(COMMAND_PREFIX.length);
    const segs = path.split('/');
    if (isSafeRelPath(path) && segs.length === 2 && segs.every((s) => NAME_RE.test(s))) {
      return { value: { kind: 'command', path } };
    }
  }
  return { error: `${rel}: unknown target claude: ${JSON.stringify(raw)} (expected 'skill' or 'command:<subdir>/<file>')` };
}

/** Parse a skill's targets mapping: { value } or { errors }. */
function parseTargets(rel, targets) {
  if (!isPlainObject(targets)) return { errors: [`${rel}: missing targets mapping`] };
  const errors = Object.keys(targets).filter((k) => !SKILL_TARGET_KEYS.includes(k)).map((k) => `${rel}: unknown target '${k}'`);
  const claude = claudeTarget(rel, targets.claude);
  if (claude.error) errors.push(claude.error);
  const codex = targets.codex;
  if (codex !== 'skill' && codex !== 'none') errors.push(`${rel}: unknown target codex: ${JSON.stringify(codex)} (expected 'skill' or 'none')`);
  const implicit = targets.codex_implicit ?? true;
  if (typeof implicit !== 'boolean') errors.push(`${rel}: codex_implicit must be true or false`);
  else if (!implicit && codex !== 'skill') errors.push(`${rel}: codex_implicit requires codex: skill`);
  if (errors.length) return { errors };
  return { value: { claude: claude.value, codex, codexImplicit: implicit } };
}

/** The skill directory's override bodies: { overrides } or { errors }. Unknown entries are errors. */
function readOverrides(root, dirRel) {
  const overrides = {};
  const errors = [];
  const byFile = Object.fromEntries(Object.entries(OVERRIDE_FILES).map(([t, f]) => [f, t]));
  for (const entry of readdirSync(join(root, dirRel)).sort()) {
    if (entry === SKILL_FILE || IGNORED_NAMES.has(entry)) continue;
    const rel = `${dirRel}/${entry}`;
    if (!byFile[entry]) { errors.push(`${rel}: unexpected file in a skill source`); continue; }
    const read = readRegular(root, rel);
    if (read.error) errors.push(read.error);
    else overrides[byFile[entry]] = read.text;
  }
  return errors.length ? { errors } : { overrides };
}

/** Read one skill source directory: { skill } or { errors }. */
async function readSkill(root, name) {
  const dirRel = `${SKILLS_DIR}/${name}`;
  const st = lstatOrNull(join(root, dirRel));
  if (!st.isDirectory()) return { errors: [`${dirRel}: not a directory (symlinks are refused)`] };
  const rel = `${dirRel}/${SKILL_FILE}`;
  const read = readRegular(root, rel);
  if (read.error) return { errors: [read.error] };
  const fm = await parseFrontmatter(rel, read.text);
  if (fm.error) return { errors: [fm.error] };
  const errors = identityErrors(rel, fm.data, SKILL_KEYS, name);
  const targets = parseTargets(rel, fm.data.targets);
  const over = readOverrides(root, dirRel);
  errors.push(...(targets.errors ?? []), ...(over.errors ?? []));
  if (!errors.length && over.overrides.codex !== undefined && targets.value.codex === 'none') {
    errors.push(`${dirRel}/${OVERRIDE_FILES.codex}: override for codex, but codex: none`);
  }
  if (errors.length) return { errors };
  const { description } = fm.data;
  return { skill: { name, description: description.trim(), targets: targets.value, body: fm.body, overrides: over.overrides, source: rel } };
}

/** Errors in an agent's Claude fields (model, tools, roles) and codex mapping. */
function agentFieldErrors(rel, data) {
  const errors = AGENT_REQUIRED.filter((k) => k !== 'name' && k !== 'description' && data[k] === undefined).map((k) => `${rel}: missing ${k}`);
  if (data.model !== undefined && !isNonEmptyString(data.model)) errors.push(`${rel}: model must be a non-empty string`);
  const tools = data.tools;
  if (tools !== undefined && !isNonEmptyString(tools) && !(Array.isArray(tools) && tools.length && tools.every(isNonEmptyString))) {
    errors.push(`${rel}: tools must be a non-empty string or list of strings`);
  }
  if (data.roles !== undefined && !(Array.isArray(data.roles) && data.roles.every(isNonEmptyString))) {
    errors.push(`${rel}: roles must be a list of strings`);
  }
  if (data.codex === undefined) return errors;
  if (!isPlainObject(data.codex)) return [...errors, `${rel}: codex must be a mapping`];
  errors.push(...Object.keys(data.codex).filter((k) => k !== 'sandbox_mode').map((k) => `${rel}: unknown target codex.${k}`));
  const mode = data.codex.sandbox_mode;
  if (mode !== undefined && !SANDBOX_MODES.includes(mode)) errors.push(`${rel}: unknown codex.sandbox_mode ${JSON.stringify(mode)}`);
  return errors;
}

/** Read one agent source file: { agent } or { errors }. */
async function readAgent(root, file) {
  const rel = `${AGENTS_DIR}/${file}`;
  if (!file.endsWith('.md')) return { errors: [`${rel}: agent sources must be .md files`] };
  const read = readRegular(root, rel);
  if (read.error) return { errors: [read.error] };
  const fm = await parseFrontmatter(rel, read.text);
  if (fm.error) return { errors: [fm.error] };
  const { data } = fm;
  const errors = [...identityErrors(rel, data, AGENT_KEYS, file.slice(0, -'.md'.length)), ...agentFieldErrors(rel, data)];
  if (errors.length) return { errors };
  const tools = Array.isArray(data.tools) ? data.tools.join(', ') : data.tools.trim();
  return {
    agent: {
      name: data.name, description: data.description.trim(), model: data.model.trim(), tools,
      roles: data.roles, sandboxMode: data.codex?.sandbox_mode, body: fm.body, source: rel,
    },
  };
}

/** Sorted entry names of a source directory: { names } ([] when absent) or { error } (symlink). */
function listSourceDir(root, rel) {
  const st = lstatOrNull(join(root, rel));
  if (!st) return { names: [] };
  if (!st.isDirectory()) return { error: `${rel}: not a directory (symlinks are refused)` };
  return { names: readdirSync(join(root, rel)).filter((n) => !IGNORED_NAMES.has(n)).sort() };
}

/** Run `read` over every entry of a source dir, collecting values and errors. */
async function collect(root, rel, read, key, out) {
  const listed = listSourceDir(root, rel);
  if (listed.error) { out.errors.push(listed.error); return; }
  for (const name of listed.names) {
    const got = await read(root, name);
    if (got.errors) out.errors.push(...got.errors);
    else out[key].push(got[key.slice(0, -1)]);
  }
}

/**
 * Read and validate every source under <root>/.rad/. Never throws.
 *
 * @param {string} root
 * @returns {Promise<{ ok: true, sources: { skills: object[], agents: object[] } } | { ok: false, errors: string[] }>}
 */
export async function readSources(root) {
  try {
    const st = lstatOrNull(join(root, SOURCE_DIR));
    if (!st) return { ok: false, errors: [`${SOURCE_DIR}/: no source directory at ${root}`] };
    if (!st.isDirectory()) return { ok: false, errors: [`${SOURCE_DIR}/: not a directory (symlinks are refused)`] };
    const out = { skills: [], agents: [], errors: [] };
    await collect(root, SKILLS_DIR, readSkill, 'skills', out);
    await collect(root, AGENTS_DIR, readAgent, 'agents', out);
    if (out.errors.length) return { ok: false, errors: out.errors };
    return { ok: true, sources: { skills: out.skills, agents: out.agents } };
  } catch (err) {
    return { ok: false, errors: [`${SOURCE_DIR}/: cannot read sources: ${err.message}`] };
  }
}

// Rendering

/** The marker line for a generated file of `kind` ('md' | 'hash'). */
function markerLine(kind, source) {
  const text = `${GENERATED_MARKER} (source: ${source})`;
  return kind === 'md' ? `<!-- ${text} -->` : `# ${text}`;
}

/**
 * True when `content` carries the generated marker in its defined position:
 * the first line (`#` comment), or the line right after the frontmatter (HTML comment).
 */
export function hasGeneratedMarker(content) {
  const lines = content.split('\n');
  if (lines[0].startsWith('# ') && lines[0].includes(GENERATED_MARKER)) return true;
  if (lines[0] !== '---') return false;
  const close = lines.indexOf('---', 1);
  const next = close > 0 ? lines[close + 1] ?? '' : '';
  return next.startsWith('<!-- ') && next.includes(GENERATED_MARKER);
}

/** A YAML scalar: plain when safe, otherwise a JSON (= YAML double-quoted) string. */
const yamlScalar = (v) => (PLAIN_SCALAR.test(v) && v.trim() === v && !YAML_RESERVED.test(v) ? v : JSON.stringify(v));
/** A TOML basic string with JSON-compatible escapes (DEL escaped too). */
const tomlString = (v) => JSON.stringify(v).replace(/\u007f/g, '\\u007f');
/** Body normalized for output: no leading blank lines, one trailing newline. */
const normalizeBody = (body) => `${body.replace(/^\n+/, '').trimEnd()}\n`;

/** A markdown file: frontmatter lines, marker, blank line, body. */
function renderMarkdown(frontmatter, source, body) {
  return `---\n${frontmatter.join('\n')}\n---\n${markerLine('md', source)}\n\n${normalizeBody(body)}`;
}

/** Substitute body tokens for `target`; unknown tokens (or any token when `allowArgs` is false) are errors. */
function substituteTokens(rel, body, target, allowArgs) {
  const bad = [...body.matchAll(TOKEN_RE)].map((m) => m[1]).filter((t) => !allowArgs || t !== ARGS_TOKEN);
  if (bad.length) return { error: `${rel}: unknown token {{${bad[0]}}}` };
  return { body: body.replace(TOKEN_RE, () => ARGS_TEXT[target]) };
}

/** The body `target` renders, with its source path for error messages. */
function skillBody(skill, target) {
  if (skill.overrides[target] === undefined) return { rel: skill.source, text: skill.body };
  return { rel: `${dirname(skill.source)}/${OVERRIDE_FILES[target]}`, text: skill.overrides[target] };
}

/** Outputs of one skill source: { outputs } or { errors }. */
function renderSkill(skill) {
  const outputs = [];
  const errors = [];
  const desc = `description: ${JSON.stringify(skill.description)}`;
  const emit = (target, path, frontmatter) => {
    const { rel, text } = skillBody(skill, target);
    const sub = substituteTokens(rel, text, target, true);
    if (sub.error) errors.push(sub.error);
    else outputs.push({ path, content: renderMarkdown(frontmatter, skill.source, sub.body), source: skill.source });
  };
  const { claude, codex, codexImplicit } = skill.targets;
  if (claude.kind === 'command') emit('claude', `.claude/commands/${claude.path}.md`, [desc]);
  else emit('claude', `.claude/skills/${skill.name}/${SKILL_FILE}`, [`name: ${skill.name}`, desc]);
  if (codex === 'skill') emit('codex', `.agents/skills/${skill.name}/${SKILL_FILE}`, [`name: ${skill.name}`, desc]);
  if (codex === 'skill' && !codexImplicit) {
    const yaml = `${markerLine('hash', skill.source)}\npolicy:\n  allow_implicit_invocation: false\n`;
    outputs.push({ path: `.agents/skills/${skill.name}/agents/openai.yaml`, content: yaml, source: skill.source });
  }
  return errors.length ? { errors } : { outputs };
}

/** The Claude agent file: frontmatter in stable key order (name, description, model, tools, roles). */
function renderClaudeAgent(agent) {
  const fm = [`name: ${agent.name}`, `description: ${JSON.stringify(agent.description)}`, `model: ${yamlScalar(agent.model)}`, `tools: ${yamlScalar(agent.tools)}`];
  if (agent.roles !== undefined) fm.push(`roles: [${agent.roles.map(yamlScalar).join(', ')}]`);
  return renderMarkdown(fm, agent.source, agent.body);
}

/** The Codex agent TOML: { content } or { error } when the body cannot be a TOML literal string. */
function renderCodexAgent(agent) {
  const body = normalizeBody(agent.body);
  if (body.includes(TOML_LITERAL_DELIM)) return { error: `${agent.source}: body contains ${TOML_LITERAL_DELIM}, which a TOML literal string cannot hold` };
  if (TOML_LITERAL_FORBIDDEN.test(body)) return { error: `${agent.source}: body contains a control character a TOML literal string cannot hold` };
  const lines = [markerLine('hash', agent.source), `name = ${tomlString(agent.name)}`, `description = ${tomlString(agent.description)}`];
  if (agent.sandboxMode !== undefined) lines.push(`sandbox_mode = ${tomlString(agent.sandboxMode)}`);
  lines.push(`developer_instructions = ${TOML_LITERAL_DELIM}`, `${body}${TOML_LITERAL_DELIM}`);
  return { content: `${lines.join('\n')}\n` };
}

/** Outputs of one agent source: { outputs } or { errors }. */
function renderAgent(agent) {
  const tokens = substituteTokens(agent.source, agent.body, 'claude', false);
  if (tokens.error) return { errors: [tokens.error] };
  const toml = renderCodexAgent(agent);
  if (toml.error) return { errors: [toml.error] };
  return {
    outputs: [
      { path: `.claude/agents/${agent.name}.md`, content: renderClaudeAgent(agent), source: agent.source },
      { path: `.codex/agents/${agent.name}.toml`, content: toml.content, source: agent.source },
    ],
  };
}

/** Errors for output paths emitted by more than one source. */
function duplicateErrors(outputs) {
  const seen = new Map();
  const errors = [];
  for (const o of outputs) {
    if (seen.has(o.path)) errors.push(`${o.source}: output ${o.path} is also emitted by ${seen.get(o.path)}`);
    else seen.set(o.path, o.source);
  }
  return errors;
}

/**
 * Render every output of the validated sources. Never throws.
 *
 * @param {{ skills: object[], agents: object[] }} sources - from readSources
 * @returns {{ ok: true, outputs: { path: string, content: string, source: string }[] } | { ok: false, errors: string[] }}
 *   outputs are sorted by path.
 */
export function renderOutputs(sources) {
  const outputs = [];
  const errors = [];
  for (const got of [...sources.skills.map(renderSkill), ...sources.agents.map(renderAgent)]) {
    if (got.errors) errors.push(...got.errors);
    else outputs.push(...got.outputs);
  }
  errors.push(...duplicateErrors(outputs));
  if (errors.length) return { ok: false, errors };
  return { ok: true, outputs: outputs.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0)) };
}

// Planning and applying

/** Why an output path cannot be written (a symlinked or non-directory ancestor), or ''. */
function ancestorProblem(root, rel) {
  const segs = rel.split('/');
  for (let i = 1; i < segs.length; i++) {
    const st = lstatOrNull(join(root, ...segs.slice(0, i)));
    if (!st) return '';
    if (!st.isDirectory()) return `${segs.slice(0, i).join('/')} is not a directory (symlinks are refused)`;
  }
  return '';
}

/** Classify one output against the file on disk: 'write' | 'unchanged' | { conflict }. */
function classifyOutput(root, output) {
  const ancestor = ancestorProblem(root, output.path);
  if (ancestor) return { conflict: ancestor };
  const st = lstatOrNull(join(root, output.path));
  if (!st) return 'write';
  if (!st.isFile()) return { conflict: 'not a regular file (symlinks are refused)' };
  const current = readFileSync(join(root, output.path), 'utf8');
  if (!hasGeneratedMarker(current)) return { conflict: 'existing file has no generated marker; it is never overwritten' };
  return current === output.content ? 'unchanged' : 'write';
}

/** Marked regular files under the output roots (sorted posix paths), never following a symlink. */
function markedFiles(root) {
  const out = [];
  const walk = (rel) => {
    const st = lstatOrNull(join(root, rel));
    if (!st || !st.isDirectory()) return;
    for (const entry of readdirSync(join(root, rel), { withFileTypes: true })) {
      const child = `${rel}/${entry.name}`;
      if (entry.isDirectory()) walk(child);
      else if (entry.isFile() && hasGeneratedMarker(readFileSync(join(root, child), 'utf8'))) out.push(child);
    }
  };
  OUTPUT_ROOTS.forEach(walk);
  return out.sort();
}

/**
 * Compare rendered outputs with the files under `root`. Reads only.
 *
 * @param {string} root
 * @param {{ path: string, content: string, source: string }[]} outputs - from renderOutputs
 * @returns {{ writes: object[], unchanged: string[], drift: string[], orphans: string[], conflicts: { path: string, reason: string }[] }}
 *   writes: the outputs to write (missing or differing; same set as drift).
 *   orphans: marked files under OUTPUT_ROOTS that no output names.
 */
export function planGenerate(root, outputs) {
  const plan = { writes: [], unchanged: [], drift: [], orphans: [], conflicts: [] };
  for (const output of outputs) {
    const kind = classifyOutput(root, output);
    if (kind === 'unchanged') plan.unchanged.push(output.path);
    else if (kind === 'write') { plan.writes.push(output); plan.drift.push(output.path); }
    else plan.conflicts.push({ path: output.path, reason: kind.conflict });
  }
  const named = new Set(outputs.map((o) => o.path));
  plan.orphans = markedFiles(root).filter((p) => !named.has(p));
  return plan;
}

/**
 * Write a plan's outputs, creating parent directories. Throws when the plan
 * has conflicts or a target turned into a symlink since planning.
 *
 * @param {string} root
 * @param {{ writes: object[], conflicts: object[] }} plan - from planGenerate
 * @returns {{ wrote: string[] }}
 */
export function applyGenerate(root, plan) {
  if (plan.conflicts.length) throw new Error(`refusing to write: ${plan.conflicts.length} conflict(s), first ${plan.conflicts[0].path}`);
  for (const output of plan.writes) {
    const problem = ancestorProblem(root, output.path);
    const st = lstatOrNull(join(root, output.path));
    if (problem || (st && !st.isFile())) throw new Error(`refusing to write ${output.path}: ${problem || 'not a regular file'}`);
    mkdirSync(dirname(join(root, output.path)), { recursive: true });
    writeFileSync(join(root, output.path), output.content);
  }
  return { wrote: plan.writes.map((o) => o.path) };
}
