/**
 * pr-body.js — the pure deliver PR title/body builder behind `rad pr-body`.
 *
 * Deterministic: no I/O, no clock, no randomness. Identical inputs always
 * yield byte-identical output. Inputs that could not be gathered arrive as
 * `{ unavailable: reason }` and render as a reason line — a broken input never
 * blocks the PR. The body NEVER carries a closing keyword (`Closes #N` …):
 * issue closure is the architect's call at merge, not the agent's.
 */
import { planHeading, planIssueNumber } from './plan-commit.js';

/** Commit lines rendered before the remainder is summarized. */
export const MAX_COMMITS = 100;
/** The `wave-attempt` outcome that marks a wave as passed (see harness/spine.js). */
const SUCCESS_OUTCOME = 'success';
const WAVE_EVENT_TYPES = new Set(['wave-attempt', 'wave-started']);
/** The `wave-started` data.kind that marks rad deliver's end-of-run test wave. */
const TEST_WAVE_KIND = 'tests';
const TEST_WAVE_LABEL = ' (test wave)';
/** parseWaveResult's default for an absent task field (harness/adapters/agent/contract.js). */
const NO_VALUE = '—';
const STATUS_ICONS = { complete: '✓', done_with_concerns: '⚠' };
const ICON_PRESENT = '✓';
const ICON_MISSING = '✗';
const ICON_UNRESOLVABLE = '?';
const FOOTER = 'Generated by rad deliver from the plan and the event log.';
const SECTION_SEPARATOR = '\n\n';

/** Same keyword set as scripts/open-pr.sh CLOSING_KEYWORD_RE, case-insensitive. */
const CLOSING_KEYWORD_RE = /\b(close[sd]?|fix(?:e[sd])?|resolve[sd]?)(\s+)#([0-9]+)/gi;
const LINE_BREAK_RE = /\s*[\r\n]+\s*/g;

// Tests-to-Write parsing — a port of scripts/check-tests-present.sh.
const TESTS_SECTION_RE = /^## Tests to Write/;
const ANY_SECTION_RE = /^## /;
const LIST_ITEM_RE = /^- /;
/** The bash `—[[:space:]]+[^[:space:]].` rule: an em-dash then a path. */
const PATH_REFERENCE_RE = /—\s+\S./;
const FILE_SEPARATOR = '— ';
const ANNOTATED_PATH_RE = /^(.*\S)\s+\([^()]*\)$/;
const ANNOTATION_ONLY_RE = /^\([^()]*\)$/;
const PLACEHOLDER_PATH = '[file]';

/**
 * Defang GitHub/GitLab closing keywords: `fixes #12` → `fixes issue 12`. The
 * keyword keeps its original case; a bare `#4` is left alone.
 *
 * @param {string} text
 * @returns {string}
 */
export function neutralizeClosingKeywords(text) {
  if (typeof text !== 'string') throw new TypeError('neutralizeClosingKeywords: text must be a string');
  return text.replace(CLOSING_KEYWORD_RE, (_m, keyword, space, n) => `${keyword}${space}issue ${n}`);
}

/** Agent- or plan-written text made safe for one Markdown line. */
function safeText(value) {
  if (typeof value !== 'string') return NO_VALUE;
  return neutralizeClosingKeywords(value.replace(LINE_BREAK_RE, ' ').trim());
}

function eventData(event) {
  return event && typeof event === 'object' && event.data && typeof event.data === 'object'
    ? event.data
    : null;
}

/**
 * Per wave, the tasks of its LAST passing `wave-attempt` (null when that
 * attempt recorded no task array). Waves with no passing attempt are absent.
 *
 * @param {Array<object>} history - the feature's events, in log order
 * @returns {Map<number, Array<object>|null>}
 */
export function lastPassingTasks(history) {
  if (!Array.isArray(history)) throw new TypeError('lastPassingTasks: history must be an array');
  const passing = new Map();
  for (const event of history) {
    const data = eventData(event);
    if (event?.type !== 'wave-attempt' || !data || data.outcome !== SUCCESS_OUTCOME) continue;
    if (!Number.isInteger(data.wave)) continue;
    passing.set(data.wave, Array.isArray(data.tasks) ? data.tasks : null);
  }
  return passing;
}

/** Every wave number named by a wave-attempt or wave-started event, ascending. */
function waveNumbers(history) {
  const waves = new Set();
  for (const event of history) {
    const data = eventData(event);
    if (WAVE_EVENT_TYPES.has(event?.type) && data && Number.isInteger(data.wave)) waves.add(data.wave);
  }
  return [...waves].sort((a, b) => a - b);
}

/** Every wave number with a `wave-started` event whose data.kind is the test-wave kind. */
function testWaveNumbers(history) {
  const waves = new Set();
  for (const event of history) {
    const data = eventData(event);
    if (event?.type !== 'wave-started' || !data || data.kind !== TEST_WAVE_KIND) continue;
    if (Number.isInteger(data.wave)) waves.add(data.wave);
  }
  return waves;
}

/** The path a `## Tests to Write` item names, or null when unresolvable. */
function itemPath(line) {
  if (!PATH_REFERENCE_RE.test(line)) return null;
  const sep = line.lastIndexOf(FILE_SEPARATOR);
  let path = (sep === -1 ? line : line.slice(sep + FILE_SEPARATOR.length)).replaceAll('`', '').trim();
  const annotated = ANNOTATED_PATH_RE.exec(path);
  if (annotated) path = annotated[1];
  if (path === '' || path === PLACEHOLDER_PATH || ANNOTATION_ONLY_RE.test(path)) return null;
  return path;
}

/**
 * The `## Tests to Write` items, parsed exactly as check-tests-present.sh does:
 * `- ` lines inside the section; the path follows the LAST `— `.
 *
 * @param {string} planText
 * @returns {Array<{path: string}|{unresolvable: string}>}
 */
export function testsToWritePaths(planText) {
  if (typeof planText !== 'string') throw new TypeError('testsToWritePaths: planText must be a string');
  const items = [];
  let inSection = false;
  for (const line of planText.split('\n')) {
    if (TESTS_SECTION_RE.test(line)) { inSection = true; continue; }
    if (ANY_SECTION_RE.test(line)) { inSection = false; continue; }
    if (!inSection || !LIST_ITEM_RE.test(line)) continue;
    const path = itemPath(line);
    items.push(path === null ? { unresolvable: line } : { path });
  }
  return items;
}

function isUnavailable(input) {
  return input !== null && typeof input === 'object' && !Array.isArray(input) && 'unavailable' in input;
}

function taskLine(task) {
  const t = task && typeof task === 'object' ? task : {};
  const status = safeText(t.status);
  const icon = STATUS_ICONS[t.status] ?? `[${status}]`;
  const concern = safeText(t.concern);
  const suffix = concern === NO_VALUE ? '' : ` — concern: ${concern}`;
  return `- ${icon} ${safeText(t.title)} — ${safeText(t.commit)}${suffix}`;
}

function waveBlock(wave, passing, testWaves) {
  const heading = `### Wave ${wave}${testWaves.has(wave) ? TEST_WAVE_LABEL : ''}`;
  if (!passing.has(wave)) return `${heading}\n- (no passing attempt recorded)`;
  const tasks = passing.get(wave);
  if (tasks === null || tasks.length === 0) return `${heading}\n- (no task details recorded)`;
  return [heading, ...tasks.map(taskLine)].join('\n');
}

function wavesSection(history) {
  const waves = waveNumbers(history);
  if (waves.length === 0) return '## Waves\n- (none recorded)';
  const passing = lastPassingTasks(history);
  const testWaves = testWaveNumbers(history);
  return ['## Waves', ...waves.map((w) => waveBlock(w, passing, testWaves))].join(SECTION_SEPARATOR);
}

function commitsSection(commits) {
  const heading = '## Commits';
  if (isUnavailable(commits)) return `${heading}\n- (commit list unavailable: ${safeText(commits.unavailable)})`;
  if (!Array.isArray(commits)) throw new TypeError('buildPrBody: commits must be an array or { unavailable }');
  if (commits.length === 0) return `${heading}\n- (none)`;
  const lines = commits.slice(0, MAX_COMMITS).map((c) => `- ${safeText(c?.hash)} ${safeText(c?.subject)}`);
  if (commits.length > MAX_COMMITS) lines.push(`- … and ${commits.length - MAX_COMMITS} more`);
  return [heading, ...lines].join('\n');
}

function testLine(item) {
  if (item && typeof item === 'object' && 'unresolvable' in item) {
    return `- ${ICON_UNRESOLVABLE} ${safeText(item.unresolvable)} (unresolvable)`;
  }
  const path = safeText(item?.path);
  return item?.present === true ? `- ${ICON_PRESENT} ${path}` : `- ${ICON_MISSING} ${path} (missing)`;
}

function testsSection(tests) {
  const heading = '## Tests to Write';
  if (isUnavailable(tests)) return `${heading}\n- (test check unavailable: ${safeText(tests.unavailable)})`;
  if (!Array.isArray(tests)) throw new TypeError('buildPrBody: tests must be an array or { unavailable }');
  if (tests.length === 0) return `${heading}\n- (none declared)`;
  return [heading, ...tests.map(testLine)].join('\n');
}

function checksSection(scope) {
  const heading = '## Checks';
  if (isUnavailable(scope)) return `${heading}\n- check-scope: unavailable (${safeText(scope.unavailable)})`;
  if (scope?.passed === true) return `${heading}\n- check-scope: passed`;
  if (scope?.passed !== false || !Array.isArray(scope.violations)) {
    throw new TypeError('buildPrBody: scope must be { passed: true }, { passed: false, violations }, or { unavailable }');
  }
  const files = scope.violations.map((f) => `  - ${safeText(f)}`);
  return [heading, `- check-scope: ${scope.violations.length} violation(s)`, ...files].join('\n');
}

function assertInputs({ feature, planPath, planText, history }) {
  for (const [name, value] of Object.entries({ feature, planPath, planText })) {
    if (typeof value !== 'string') throw new TypeError(`buildPrBody: ${name} must be a string`);
  }
  if (!Array.isArray(history)) throw new TypeError('buildPrBody: history must be an array');
}

/**
 * The deliver PR's title and body.
 *
 * @param {object} input
 * @param {string} input.feature
 * @param {string} input.planPath
 * @param {string} input.planText
 * @param {Array<object>} input.history - the feature's events
 * @param {Array<{hash, subject}>|{unavailable: string}} input.commits
 * @param {Array<{path, present}|{unresolvable}>|{unavailable: string}} input.tests
 * @param {{passed: true}|{passed: false, violations: string[]}|{unavailable: string}} input.scope
 * @returns {{ title: string, body: string }}
 */
export function buildPrBody(input) {
  if (!input || typeof input !== 'object') throw new TypeError('buildPrBody: input must be an object');
  assertInputs(input);
  const { feature, planPath, planText, history, commits, tests, scope } = input;
  const heading = planHeading(planText);
  const issue = planIssueNumber(planText);
  const sections = [
    `Plan: \`${safeText(planPath)}\``,
    ...(issue === null ? [] : [`Issue: #${issue}`]),
    wavesSection(history),
    commitsSection(commits),
    testsSection(tests),
    checksSection(scope),
    FOOTER,
  ];
  return {
    title: `Deliver: ${safeText(heading ?? feature)}`,
    body: `${sections.join(SECTION_SEPARATOR)}\n`,
  };
}
