import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  MAX_COMMITS,
  buildPrBody,
  lastPassingTasks,
  testsToWritePaths,
  neutralizeClosingKeywords,
} from '../pr-body.js';
import { planHeading } from '../plan-commit.js';

const PLAN_PATH = '.agents/plans/demo.md';
const CLOSING_RE = /\b(close[sd]?|fix(e[sd])?|resolve[sd]?) #[0-9]+/i;

function planText({ heading = 'Demo Feature', issue = '42', tests = null } = {}) {
  const lines = [];
  if (heading !== null) lines.push(`# Plan: ${heading}`);
  lines.push('Status: approved');
  if (issue !== null) lines.push(`Issue: ${issue}`);
  lines.push('', '## Context', 'x', '');
  if (tests !== null) lines.push('## Tests to Write', ...tests, '');
  lines.push('## Wave Plan', '### Wave 1 — sequential');
  return lines.join('\n');
}

const task = (title, status = 'complete', commit = 'abc1234', concern = '—') =>
  ({ title, status, commit, concern, error: '—' });
const started = (wave) => ({ type: 'wave-started', data: { wave, attempt: 1 } });
const attempt = (wave, outcome, tasks) =>
  ({ type: 'wave-attempt', data: { wave, attempt: 1, outcome, usage: {}, ...(tasks ? { tasks } : {}) } });

function input(overrides = {}) {
  return {
    feature: 'demo',
    planPath: PLAN_PATH,
    planText: planText(),
    history: [],
    commits: [],
    tests: [],
    scope: { passed: true },
    ...overrides,
  };
}

/** One `## ` section of a body: from its heading to the next `## ` section or the footer. */
function section(body, heading) {
  const start = body.indexOf(`${heading}\n`);
  const rest = body.slice(start);
  const end = rest.search(/\n\n(## |Generated by)/);
  return end === -1 ? rest : rest.slice(0, end);
}

test('snapshot: a two-wave body renders exactly', () => {
  const history = [
    { type: 'approved', data: {} },
    started(1),
    attempt(1, 'success', [task('Build the thing', 'complete', 'aaa1111'),
      task('Wire it', 'done_with_concerns', 'bbb2222', 'flaky edge')]),
    started(2),
    attempt(2, 'success', [task('Test it', 'complete', 'ccc3333')]),
  ];
  const { title, body } = buildPrBody(input({
    history,
    commits: [{ hash: 'aaa1111', subject: 'deliver(demo): build' }, { hash: 'bbb2222', subject: 'deliver(demo): wire' }],
    tests: [{ path: 'harness/test/a.test.js', present: true }, { path: 'harness/test/b.test.js', present: false },
      { unresolvable: '- [ ] something vague' }],
    scope: { passed: false, violations: ['src/x.js', 'src/y.js'] },
  }));
  assert.equal(title, 'Deliver: Demo Feature');
  assert.equal(body, [
    'Plan: `.agents/plans/demo.md`',
    '',
    'Issue: #42',
    '',
    '## Waves',
    '',
    '### Wave 1',
    '- ✓ Build the thing — aaa1111',
    '- ⚠ Wire it — bbb2222 — concern: flaky edge',
    '',
    '### Wave 2',
    '- ✓ Test it — ccc3333',
    '',
    '## Commits',
    '- aaa1111 deliver(demo): build',
    '- bbb2222 deliver(demo): wire',
    '',
    '## Tests to Write',
    '- ✓ harness/test/a.test.js',
    '- ✗ harness/test/b.test.js (missing)',
    '- ? - [ ] something vague (unresolvable)',
    '',
    '## Checks',
    '- check-scope: 2 violation(s)',
    '  - src/x.js',
    '  - src/y.js',
    '',
    'Generated by rad deliver from the plan and the event log.',
    '',
  ].join('\n'));
});

test('title: heading when present, feature fallback when absent', () => {
  assert.equal(buildPrBody(input()).title, 'Deliver: Demo Feature');
  assert.equal(buildPrBody(input({ planText: planText({ heading: null }) })).title, 'Deliver: demo');
});

test('issue: rendered as a plain reference, omitted when absent, never a closing keyword', () => {
  const withIssue = buildPrBody(input()).body;
  assert.match(withIssue, /^Issue: #42$/m);
  assert.doesNotMatch(withIssue, CLOSING_RE);
  const without = buildPrBody(input({ planText: planText({ issue: null }) })).body;
  assert.doesNotMatch(without, /Issue:/);
  assert.ok(without.startsWith('Plan: `.agents/plans/demo.md`\n\n## Waves'));
});

test('waves: a retried wave renders its LAST passing attempt', () => {
  const history = [
    started(1), attempt(1, 'success', [task('first try')]),
    attempt(1, 'failed', [task('broken', 'blocked_code')]),
    attempt(1, 'success', [task('second try')]),
  ];
  const waves = section(buildPrBody(input({ history })).body, '## Waves');
  assert.match(waves, /second try/);
  assert.doesNotMatch(waves, /first try|broken/);
});

test('waves: passing attempt without tasks, no passing attempt, and none at all', () => {
  const history = [started(1), attempt(1, 'success'), started(2), attempt(2, 'failed', [task('x')]), started(3)];
  assert.equal(section(buildPrBody(input({ history })).body, '## Waves'), [
    '## Waves', '', '### Wave 1', '- (no task details recorded)', '',
    '### Wave 2', '- (no passing attempt recorded)', '', '### Wave 3', '- (no passing attempt recorded)',
  ].join('\n'));
  assert.equal(section(buildPrBody(input()).body, '## Waves'), '## Waves\n- (none recorded)');
});

test('waves: numeric order, unknown status rendered as a word', () => {
  const history = [attempt(10, 'success', [task('ten')]), attempt(2, 'success', [task('two', 'blocked_code')])];
  const waves = section(buildPrBody(input({ history })).body, '## Waves');
  assert.ok(waves.indexOf('### Wave 2') < waves.indexOf('### Wave 10'));
  assert.match(waves, /^- \[blocked_code\] two — abc1234$/m);
});

test('waves: a wave-started kind tests marks that wave only; no kind or another kind renders unchanged', () => {
  const testStarted = (wave) => ({ type: 'wave-started', data: { wave, attempt: 1, kind: 'tests' } });
  const otherKind = { type: 'wave-started', data: { wave: 2, attempt: 2, kind: 'other' } };
  const history = [
    started(1), attempt(1, 'success', [task('impl')]),
    started(2), otherKind, attempt(2, 'success', [task('more')]),
    testStarted(3), attempt(3, 'success', [task('tests', 'complete', 'def5678')]),
  ];
  assert.equal(section(buildPrBody(input({ history })).body, '## Waves'), [
    '## Waves', '', '### Wave 1', '- ✓ impl — abc1234', '',
    '### Wave 2', '- ✓ more — abc1234', '',
    '### Wave 3 (test wave)', '- ✓ tests — def5678',
  ].join('\n'));
});

test('waves: a test wave with no passing attempt keeps the marker; kind on wave-attempt alone does not mark', () => {
  const history = [
    { type: 'wave-started', data: { wave: 1, attempt: 1, kind: 'tests' } },
    { type: 'wave-attempt', data: { wave: 2, attempt: 1, outcome: 'success', kind: 'tests', tasks: [task('x')] } },
  ];
  const waves = section(buildPrBody(input({ history })).body, '## Waves');
  assert.match(waves, /^### Wave 1 \(test wave\)\n- \(no passing attempt recorded\)$/m);
  assert.match(waves, /^### Wave 2$/m);
});

test('waves: concern shown when set, hidden when the default dash', () => {
  const history = [attempt(1, 'success', [task('a', 'complete', 'c1'), task('b', 'done_with_concerns', 'c2', 'slow')])];
  const waves = section(buildPrBody(input({ history })).body, '## Waves');
  assert.match(waves, /^- ✓ a — c1$/m);
  assert.match(waves, /^- ⚠ b — c2 — concern: slow$/m);
});

test('commits: capped at MAX_COMMITS with a remainder line; empty renders (none)', () => {
  const commits = Array.from({ length: MAX_COMMITS + 5 }, (_, i) => ({ hash: `h${i}`, subject: `s${i}` }));
  const lines = section(buildPrBody(input({ commits })).body, '## Commits').split('\n');
  assert.equal(lines.length, 1 + MAX_COMMITS + 1);
  assert.equal(lines[MAX_COMMITS], `- h${MAX_COMMITS - 1} s${MAX_COMMITS - 1}`);
  assert.equal(lines.at(-1), '- … and 5 more');
  assert.equal(section(buildPrBody(input()).body, '## Commits'), '## Commits\n- (none)');
});

test('tests: empty array renders (none declared)', () => {
  assert.equal(section(buildPrBody(input()).body, '## Tests to Write'), '## Tests to Write\n- (none declared)');
});

test('unavailable inputs render their reason instead of blocking', () => {
  const { body } = buildPrBody(input({
    commits: { unavailable: 'git log failed' },
    tests: { unavailable: 'plan unreadable' },
    scope: { unavailable: 'script exited 2' },
  }));
  assert.match(body, /^- \(commit list unavailable: git log failed\)$/m);
  assert.match(body, /^- \(test check unavailable: plan unreadable\)$/m);
  assert.match(body, /^- check-scope: unavailable \(script exited 2\)$/m);
});

test('checks: passed and violation shapes', () => {
  assert.equal(section(buildPrBody(input()).body, '## Checks'), '## Checks\n- check-scope: passed');
  const failed = buildPrBody(input({ scope: { passed: false, violations: ['a.js'] } })).body;
  assert.equal(section(failed, '## Checks'), '## Checks\n- check-scope: 1 violation(s)\n  - a.js');
});

test('neutralizeClosingKeywords: every keyword form, case kept, bare refs untouched', () => {
  assert.equal(neutralizeClosingKeywords('fixes #12'), 'fixes issue 12');
  assert.equal(neutralizeClosingKeywords('Closes #3'), 'Closes issue 3');
  assert.equal(neutralizeClosingKeywords('RESOLVED #9'), 'RESOLVED issue 9');
  assert.equal(neutralizeClosingKeywords('close #1, fix #2, fixed #5, resolve #6'),
    'close issue 1, fix issue 2, fixed issue 5, resolve issue 6');
  assert.equal(neutralizeClosingKeywords('see #4'), 'see #4');
});

test('agent-written text is neutralized and multi-line text collapsed', () => {
  const history = [attempt(1, 'success', [task('Fixes #7\nand more', 'done_with_concerns', 'c1', 'line one\r\n  line two')])];
  const { body } = buildPrBody(input({
    history,
    commits: [{ hash: 'h1', subject: 'Resolves #8' }],
    scope: { passed: false, violations: ['closes #9'] },
  }));
  assert.doesNotMatch(body, CLOSING_RE);
  assert.match(body, /^- ⚠ Fixes issue 7 and more — c1 — concern: line one line two$/m);
  assert.match(body, /^- h1 Resolves issue 8$/m);
});

test('identical inputs yield identical output', () => {
  const make = () => input({ history: [attempt(1, 'success', [task('a')])], commits: [{ hash: 'h', subject: 's' }] });
  assert.deepEqual(buildPrBody(make()), buildPrBody(make()));
});

test('TypeError on bad input', () => {
  assert.throws(() => buildPrBody(null), TypeError);
  assert.throws(() => buildPrBody(input({ history: 'nope' })), TypeError);
  assert.throws(() => buildPrBody(input({ planText: 5 })), TypeError);
  assert.throws(() => buildPrBody(input({ commits: 'x' })), TypeError);
  assert.throws(() => buildPrBody(input({ scope: {} })), TypeError);
  assert.throws(() => lastPassingTasks({}), TypeError);
  assert.throws(() => testsToWritePaths(null), TypeError);
  assert.throws(() => neutralizeClosingKeywords(12), TypeError);
  assert.throws(() => planHeading(undefined), TypeError);
});

test('lastPassingTasks: only waves with a passing attempt, last one wins, null without tasks', () => {
  const m = lastPassingTasks([
    attempt(1, 'success', [task('old')]), attempt(1, 'success', [task('new')]),
    attempt(2, 'failed', [task('x')]), attempt(3, 'success'), { type: 'junk' }, null,
  ]);
  assert.deepEqual([...m.keys()], [1, 3]);
  assert.equal(m.get(1)[0].title, 'new');
  assert.equal(m.get(3), null);
});

test('testsToWritePaths: mirrors the check-tests-present.sh rule', () => {
  const text = planText({ tests: [
    '- [ ] parses input — harness/test/a.test.js',
    '- [x] desc — with — dashes — `harness/test/b.test.js`',
    '- [ ] annotated — scripts/test-c.sh (Amendment 1)',
    '- [ ] placeholder — [file]',
    '- [ ] annotation only — (later)',
    '- [ ] no path here',
    '  - indented ignored — x/y.js',
    'not a list item — x/z.js',
  ] });
  assert.deepEqual(testsToWritePaths(text), [
    { path: 'harness/test/a.test.js' },
    { path: 'harness/test/b.test.js' },
    { path: 'scripts/test-c.sh' },
    { unresolvable: '- [ ] placeholder — [file]' },
    { unresolvable: '- [ ] annotation only — (later)' },
    { unresolvable: '- [ ] no path here' },
  ]);
});

test('testsToWritePaths: no section yields no items; the section ends at the next ## heading', () => {
  assert.deepEqual(testsToWritePaths(planText()), []);
  const text = '## Tests to Write\n- [ ] a — t/a.js\n## Other\n- [ ] b — t/b.js\n';
  assert.deepEqual(testsToWritePaths(text), [{ path: 't/a.js' }]);
});

test('planHeading: heading string or null, never throws on a missing heading', () => {
  assert.equal(planHeading('# Plan:  Spaced Title  \nStatus: x'), 'Spaced Title');
  assert.equal(planHeading('Status: x\n## Context'), null);
  assert.equal(planHeading(''), null);
});
